"""
Django settings for full_auth project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9+5i6x!fye9v_2y%rkf7$1x((*-dn(c#qncwlp2x#ar0(6n-h4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "accounts.apps.AccountsConfig",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "PIL",
    "user_agents",
    "pyotp",
    "requests",
    "django_cryptography",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "accounts.middleware.CustomizedCsrfViewMiddleware",
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'full_auth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "build"), TEMPLATE_DIR],
        # Enabling Reactjs (+ React Router) and Django Templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'full_auth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Africa/Cairo"  # You can choose timezone of any country you want Continent/Capital of country
# https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568 all timezones
# Code to print all timezones:
# import pytz
# for tz in pytz.all_timezones:
# print tz

USE_I18N = True

USE_TZ = False  # set to False to remove TZ from datetime input/query formats




# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

###########################################################
# Social Login:
###############
GOOGLE_CLIENT_ID = "************************sadas.apps.googleusercontent.com"
# provide your own google client ID


############################################################
# Google SMTP for sending emails:
#################################
# Note: Google has disabled less secure apps which enables to use google account with password only
# Solution is to enable Google 2 factor authentication in order to enable App passwords in your google account
# Create new App password, then use that password here
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = ""  # Google account email
EMAIL_HOST_PASSWORD = ""  # Google account App password
EMAIL_PORT = 587
EMAIL_USE_TLS = True
############################################################

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DATE_INPUT_FORMATS': [
        "%Y-%m-%d",
        "%Y/%m/%d",
        "%d-%m-%Y",
        "%d/%m/%Y",
    ],
    "DATE_FORMAT": "%d/%m/%Y",
    'DATETIME_FORMAT': "%A %d/%m/%Y %I:%M %p",  # %A: day name, %I: hour number 12h format, %p: PM/AM
    'DATETIME_INPUT_FORMATS': [
        "%Y-%m-%d %I:%M %p",
    ],
}

# CORS Headers Configuration:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # for reactjs with django while development
]




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "build/static"),  # Including Reactjs build static files to Django static.
]
STATIC_ROOT = "static/"


##############################################################
# MEDIA TO STORE UPLOADED IMAGES:
####################################
MEDIA_URL = "media/"
MEDIA_ROOT = "media/"
##############################################################

AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_STORAGE_BUCKET_NAME = "s3-bucket-name"
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
AWS_S3_FILE_OVERWRITE = False

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
        "OPTIONS": {
            # media files/dirs will be pushed to 'media' directory within s3 bucket
            "location": "media"
        }
    },

    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
        "OPTIONS": {
            # static files/dirs will be pushed to 'static' directory within s3 bucket
            "location": "static"
        }
    }

}